project = "example-project-123456"
region = "europe-west2"
prefix = "tgnewsbot"
scheduler_cron = "*/2 * * * *"
telegram_bot_token = "123456:changeme"
telegram_chat_id = "@news_channel"
rss_feed_url = "http://feeds.bbci.co.uk/news/world/rss.xml"