name: Deploy function to Google cloud

on:
  push:
    branches:
      - master
    paths:
      - 'rssbot/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: >-
          gcloud functions deploy ${{ secrets.GCP_PREFIX }}-function
          --region="${{ secrets.GCP_REGION }}" 
          --update-env-vars TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          --update-env-vars TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          --update-env-vars RSS_FEED_URL="${{ secrets.RSS_FEED_URL }}"
          --trigger-http 
          --source=./rssbot 
          --format="json" | jq ".status"
